### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by easyWater** [react-redux-antd-es6/react#14]
有人跑起来了吗？按照文档的步骤npm start 的时候就不行了，窗口一直在闪，很多throw er;

**Comment by wangcheng1212** [comment]
![image](https://user-images.githubusercontent.com/38998191/86218584-987b9f00-bbb3-11ea-909d-88d7e862655d.png)

**Comment by easyWaterYY** [comment]
1.最好不要放在中文目录下(容易出问题)

**Comment by easyWater** [comment]
1.首先不要放在中文目录下(容易出错)
2.使用npm装包不用cnpm，如果装包失败翻墙后再试


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"leozhangj1"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月1日(星期三) 下午3:57
收件人:&nbsp;"react-redux-antd-es6/react"<react@noreply.github.com&gt;;
抄送:&nbsp;"--陌上-℃"<2575217546@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [react-redux-antd-es6/react] 运行报错 (#14)

**Comment by wangcheng1212** [comment]
![image](https://user-images.githubusercontent.com/38998191/86220657-7899aa80-bbb6-11ea-8482-98bbab258f9c.png)

**Comment by wangcheng1212** [comment]
![image](https://user-images.githubusercontent.com/38998191/86220696-86e7c680-bbb6-11ea-8da7-5104b78559c0.png)

**Comment by wangcheng1212** [comment]
感谢,已经跑起来了,但是有个报错,初始化的时候,state里没有定义children;
login.js; line148
const children = this.state.children.map(item =>

**Comment by duxianwei520** [comment]
@wangcheng1212 login.js貌似没有声明你说的这行代码呀
