### ISSUE TITLE
克隆下来说缺文件？

### ISSUE THREAD

**Issue by wuyongdec** [react-redux-antd-es6/react#2]
`ERROR in ./app/pages/house/roomDetail.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./detail/Check in /root/reactEnterpriseBackend/react/app/pages/house
 @ ./app/pages/house/roomDetail.js 66:13-38

ERROR in ./app/pages/house/houseDetail.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./detail/Check in /root/reactEnterpriseBackend/react/app/pages/house
 @ ./app/pages/house/houseDetail.js 66:13-38`

**Comment by duxianwei520** [comment]
@wuyongdec  我更新了代码  你看看  应该没啥问题了的吧

**Comment by wuyongdec** [comment]
@duxianwei520 恩，谢谢，我发现是文件名大小写问题，改了就行了

**Comment by lwx333921** [comment]
安装依赖包的时候报错     No value found for key gulp-mocha at 1:5370
npm ERR! h":"1.0.0","gulp-webpack":"0.4.1","gulp-jshint":"1.8.4","gulp-mocha":
